version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
      - ./client/resources/public/index.html:/usr/share/nginx/html/index.html
